using System;
using System.Collections.Generic;
using System.Net;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using myad;
using System.Drawing;
using System.Net.Mail;
using System.Configuration;
using System.Data.SqlClient;
using System.IO;
using System.Diagnostics;
public partial class profile_Default : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        title.Focus();
    }
    //button clear
    private void button_clear()
    {
        title.Text = string.Empty;
        rtd.Text = string.Empty;
        urls.Text = string.Empty;
        requirements.Text = string.Empty;
    }

    //Function to create html email.
    void CreateMail(Int32 code,String uname,String umail)
    {
        try
        {
            String body = htmlbody(code,1,uname);
            SendMail(body,umail,1);
            body = htmlbody(code,2,uname);
            SendMail(body,umail,2);
        }
        catch (System.Net.Mail.SmtpException exp)
        {
            Debug.Write("JJ ExceptION 2" + exp);
        }
    }
    //Fuction to create html email body.
    String htmlbody(Int32 code,Int16 var,String uname)
    {
        String body = String.Empty;
        if (var == 1)
        {
            using (StreamReader reader = new StreamReader(Server.MapPath("~/emailtemp/adreqadmin.html")))
            {
                body = reader.ReadToEnd();
            }
            body = body.Replace("{username}", "Admin");
            body = body.Replace("{message1}", "A new AD request with AD Code <b>" + code + "</b> has been generated by <b>" + uname + "</b>. Click ");
            body = body.Replace("{url}", "http://pcse944-001-site1.btempurl.com/admindash/login.aspx");
            body = body.Replace("{message2}", " to open dashboard.");
            return body;
        }
        else
        {
            using (StreamReader reader = new StreamReader(Server.MapPath("~/emailtemp/adrequser.html")))
            {
                body = reader.ReadToEnd();
            }
            body = body.Replace("{username}", uname);
            body = body.Replace("{message1}", "A new AD request with AD Code <b>" + code + "</b> has been successfully generated. Thanks for choosing us. " +
                "Click ");
            body = body.Replace("{url}", "http://pcse944-001-site1.btempurl.com/profile/login.aspx");
            body = body.Replace("{message2}", " to login to your profile.");
            return body;
        }
        
    }

    //AD id Retriever
    public void getvaljj()
    {
        Int32 val;
        String umail, uname;
        SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["myad5ConnectionString"].ConnectionString);
        try
        {
            con.Open();
            SqlCommand cmd = new SqlCommand();
            cmd.Connection = con;
            cmd.CommandText = "SELECT frmcod FROM detfrm WHERE frmregcod ='" + Session["cod"] + "' AND frmstatus = 'New' ORDER BY frmcod DESC;";
            SqlDataReader reader = cmd.ExecuteReader();
            reader.Read();
            val = Convert.ToInt32(reader["frmcod"]);
            reader.Close();
            cmd.CommandText = "SELECT email FROM register WHERE regid ='" + Session["cod"] + "';";
            reader = cmd.ExecuteReader();
            reader.Read();
            umail = Convert.ToString(reader["email"]);
            reader.Close();
            cmd.CommandText = "SELECT f_name FROM register WHERE regid ='" + Session["cod"] + "';";
            reader = cmd.ExecuteReader();
            reader.Read();
            uname = Convert.ToString(reader["f_name"]);
            reader.Close();
            CreateMail(val,uname,umail); //Call to mail creater.
        }
        catch (Exception exp)
        {
            Debug.Write("JJ ExcEpTIOn "+exp);
        }
        finally
        {
            con.Close();
        }
    }
    //End AD id Retriever
    //Mail Sender
    public void SendMail(String body,String umail,Int16 var)
    {
        MailMessage mailMessage;
        if(var == 1)
        {
            mailMessage = new MailMessage("pcse944@gmail.com", "pcse944@gmail.com");
        }
        else
        {
            mailMessage = new MailMessage("pcse944@gmail.com", umail);
        }
        mailMessage.Subject = "New AD request generated.";
        mailMessage.IsBodyHtml = true;
        mailMessage.Body = body;
        SmtpClient smtpg = new SmtpClient("smtp.gmail.com", 587);
        //smtpg.Credentials = new System.Net.NetworkCredential()
        //{
        //    UserName = "my-ad@outlook.com",
        //    Password = "password1.A"
        //};
        smtpg.EnableSsl = true;
        NetworkCredential NetworkCred = new NetworkCredential();
        NetworkCred.UserName = "pcse944@gmail.com";
        NetworkCred.Password = "password1.";
        smtpg.UseDefaultCredentials = true;
        smtpg.Credentials = NetworkCred;
        smtpg.Send(mailMessage);
    }
    //End mail sender
    //calender
    protected void ImageButton1_Click(object sender, ImageClickEventArgs e)
    {
        if (rtd.Text != string.Empty)
            Calendar1.SelectedDate = Convert.ToDateTime(rtd.Text);

        Calendar1.Visible = true;
    }

    protected void Calendar1_SelectionChanged(object sender, EventArgs e)
    {
        rtd.Text = Calendar1.SelectedDate.ToShortDateString();
        Calendar1.Visible = false;
    }

    protected void rtd_TextChanged(object sender, EventArgs e)
    {
        Calendar1.SelectedDate = Convert.ToDateTime(rtd.Text);
    }
    //calender ending
    protected void Button1_Click(object sender, EventArgs e)
    {
        clsdetfrm obj = new clsdetfrm();
        clsdetfrmprp objprp = new clsdetfrmprp();
        objprp.frmtit = title.Text;
        objprp.frmregcod = Convert.ToInt32(Session["cod"]);
        objprp.frmdate = Convert.ToDateTime(rtd.Text);
        objprp.frmurl = urls.Text;
        objprp.frmdesc = requirements.Text;
        objprp.frmreqcont = DropDownList1.SelectedValue.ToString();
        objprp.frmsubmitdate = DateTime.Now;
        objprp.frmpayment = "none";
        objprp.pdt = default(DateTime);
        objprp.rdt = default(DateTime);
        //  if (Button1.Text == "send details")
        //  {
        obj.save_rec_detfrm(objprp);
        getvaljj();
        Response.Redirect("det_view.aspx");
        button_clear();



    }

    protected void Button2_Click(object sender, EventArgs e)
    {
        button_clear();

    }

    protected void Calendar1_DayRender(object sender, DayRenderEventArgs e)
    {
        if (e.Day.Date <= DateTime.Now)
        {
            e.Cell.BackColor = ColorTranslator.FromHtml("#a9a9a9");
            e.Day.IsSelectable = false;
        }
    }
}